# Generated by Django 4.0 on 2024-04-12 20:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blogpost_published_date_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Needs to be filled out'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Need to download'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='interestingpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
